# This file was generated by GoReleaser. DO NOT EDIT.
cask "cdb" do
  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "f60321b8966b59fbb7779173eb7a85de0d771cce1c95307dab352d1a8142f29c"
      url "https://github.com/sriannamalai/CDB.CLI/releases/download/v#{version}/cdb_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "de7cb9e411cad56602af3dcbe097e160bdf37bdf502b3405a0366c400e3080b6"
      url "https://github.com/sriannamalai/CDB.CLI/releases/download/v#{version}/cdb_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4d659b88ee345d413c67ec315f196de38a033f275b5046b8f33ee945d4c389d4"
      url "https://github.com/sriannamalai/CDB.CLI/releases/download/v#{version}/cdb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0451b1d6f53cee84743badc85acdb6648560646a14a4407c0bb437a78897855c"
      url "https://github.com/sriannamalai/CDB.CLI/releases/download/v#{version}/cdb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cdb"
  desc "Interactive CouchDB command line client"
  homepage "https://github.com/sriannamalai/CDB.CLI"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cdb"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cdb"]
    end
  end

  # No zap stanza required
end
