# This file was generated by GoReleaser. DO NOT EDIT.
cask "cdb" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "16416329edcd2b0940f43c147b1787520dabaf87a4a0b3602dbeb7b7a230aed1"
      url "https://github.com/sriannamalai/CDB.CLI/releases/download/v#{version}/cdb_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2a588c378c6f80b680ecbad956c240d9219fcd01543f6cbb93f45054be9ae2f4"
      url "https://github.com/sriannamalai/CDB.CLI/releases/download/v#{version}/cdb_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c3db8c4de5cdb6455bc5b5e8ad9b7246a0a4265a9ad1064622fa492ad4a86664"
      url "https://github.com/sriannamalai/CDB.CLI/releases/download/v#{version}/cdb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "04e5d74af174ca161a4eac6f95004f8ce8e88de15f4dc08e46461b3030b64b33"
      url "https://github.com/sriannamalai/CDB.CLI/releases/download/v#{version}/cdb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cdb"
  desc "Interactive CouchDB command line client"
  homepage "https://github.com/sriannamalai/CDB.CLI"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cdb"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cdb"]
    end
  end

  # No zap stanza required
end
