# This file was generated by GoReleaser. DO NOT EDIT.
cask "cdb" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/cdb"]
    end
  end

  version "1.2.1"

  on_macos do
    on_arm do
      sha256 "a67f1c820e6677eac5370d5c357b4e2c6982f3b000f2f0c386216871212cabfa"
      url "https://github.com/sriannamalai/CDB.CLI/releases/download/v#{version}/cdb_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b89cdf4868706e9d3954bbffe99620b20887e869c2277193000759dc129bfbfe"
      url "https://github.com/sriannamalai/CDB.CLI/releases/download/v#{version}/cdb_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c2b92de5f6807af9c6ff03cac0a53fb0ced4da4ef9c232e38f6d50285ca90aec"
      url "https://github.com/sriannamalai/CDB.CLI/releases/download/v#{version}/cdb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7b1721d79f69cd42068c1d0235004375323255b123645d0d610e23eadb8dcb5b"
      url "https://github.com/sriannamalai/CDB.CLI/releases/download/v#{version}/cdb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cdb"
  desc "Interactive CouchDB command-line client"
  homepage "https://github.com/sriannamalai/CDB.CLI"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cdb"

  # No zap stanza required
end
